export const ABI = [
  // ── View: core state ─────────────────────────────────────────
  { type: "function", name: "owner",                 inputs: [], outputs: [{ type: "address" }],  stateMutability: "view" },
  { type: "function", name: "devWallet",             inputs: [], outputs: [{ type: "address" }],  stateMutability: "view" },
  { type: "function", name: "mintClosed",             inputs: [], outputs: [{ type: "bool" }],     stateMutability: "view" },
  { type: "function", name: "votingClosed",           inputs: [], outputs: [{ type: "bool" }],     stateMutability: "view" },
  { type: "function", name: "paused",                inputs: [], outputs: [{ type: "bool" }],     stateMutability: "view" },
  { type: "function", name: "maintenanceMode",       inputs: [], outputs: [{ type: "bool" }],     stateMutability: "view" },
  { type: "function", name: "MINT_PRICE",            inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "TICKET_PRICE",          inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "totalLockedPrizePool",  inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "totalGlobalVolumeETH",  inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "nationsCupPoolBalance", inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "topScorerPoolBalance",  inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "totalUnusedTickets",    inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "tournamentFinalized",   inputs: [], outputs: [{ type: "bool" }],     stateMutability: "view" },
  { type: "function", name: "topScorerFinalized",    inputs: [], outputs: [{ type: "bool" }],     stateMutability: "view" },
  { type: "function", name: "winningCountryId",      inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "finalTopScorer",        inputs: [], outputs: [{ type: "string" }],   stateMutability: "view" },
  { type: "function", name: "finalNationsCupPool",   inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "finalTopScorerPool",    inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "nationsCupFinalizedAt", inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  { type: "function", name: "topScorerFinalizedAt",  inputs: [], outputs: [{ type: "uint256" }],  stateMutability: "view" },
  // ── View: mappings / helpers ──────────────────────────────────
  {
    type: "function", name: "getAllEliminationStatus",
    inputs: [], outputs: [{ name: "eliminated", type: "bool[49]" }], stateMutability: "view",
  },
  { type: "function", name: "countryEliminated",  inputs: [{ name: "countryId", type: "uint256" }], outputs: [{ type: "bool" }],    stateMutability: "view" },
  { type: "function", name: "countryTotalSupply", inputs: [{ name: "", type: "uint256" }],           outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "userMintCount",      inputs: [{ type: "address" }, { type: "uint256" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "userUnusedTickets",  inputs: [{ type: "address" }],                    outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOf",          inputs: [{ type: "address" }, { type: "uint256" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  {
    type: "function", name: "balanceOfBatch",
    inputs: [{ name: "accounts", type: "address[]" }, { name: "ids", type: "uint256[]" }],
    outputs: [{ type: "uint256[]" }], stateMutability: "view",
  },
  { type: "function", name: "getPlayerVotes",        inputs: [{ name: "playerName", type: "string" }],                              outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getUserVotesForPlayer", inputs: [{ type: "address" }, { name: "playerName", type: "string" }],         outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "topScorerHasClaimed",   inputs: [{ type: "address" }], outputs: [{ type: "bool" }],    stateMutability: "view" },
  { type: "function", name: "nationsCupHasClaimed",  inputs: [{ type: "address" }], outputs: [{ type: "bool" }],    stateMutability: "view" },
  { type: "function", name: "pendingDevBalance",     inputs: [],                    outputs: [{ type: "uint256" }], stateMutability: "view" },
  // ── Write: user actions ───────────────────────────────────────
  { type: "function", name: "mintCountryNFT",         inputs: [{ name: "countryId", type: "uint256" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "payable" },
  { type: "function", name: "buyScorerTickets",       inputs: [{ name: "quantity", type: "uint256" }],                outputs: [], stateMutability: "payable" },
  { type: "function", name: "voteTopScorer",          inputs: [{ name: "playerName", type: "string" }, { name: "votesToUse", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "claimNationsCupRewards", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "claimTopScorerRewards",  inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "refundUnusedTickets",    inputs: [], outputs: [], stateMutability: "nonpayable" },
  // ── Write: onlyOwner ─────────────────────────────────────────
  { type: "function", name: "setMintClosed",        inputs: [{ name: "_mintClosed", type: "bool" }],    outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setVotingClosed",      inputs: [{ name: "_votingClosed", type: "bool" }],  outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setPaused",           inputs: [{ name: "_paused", type: "bool" }],        outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setMaintenanceMode",  inputs: [{ name: "_maintenance", type: "bool" }],   outputs: [], stateMutability: "nonpayable" },
  {
    type: "function", name: "eliminateCountries",
    inputs: [{ name: "loserIds", type: "uint256[]" }],
    outputs: [], stateMutability: "nonpayable",
  },
  { type: "function", name: "setDevWallet",        inputs: [{ name: "_newDevWallet", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setBaseURI",          inputs: [{ name: "_newBaseURI", type: "string" }],   outputs: [], stateMutability: "nonpayable" },
  {
    type: "function", name: "finalizeNationsCup",
    inputs: [{ name: "_winningCountryId", type: "uint256" }], outputs: [], stateMutability: "nonpayable",
  },
  {
    type: "function", name: "finalizeTopScorer",
    inputs: [{ name: "playerName", type: "string" }], outputs: [], stateMutability: "nonpayable",
  },
  { type: "function", name: "withdrawUnclaimedNationsCup", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "withdrawUnclaimedTopScorer",  inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "withdrawPendingDev",          inputs: [], outputs: [], stateMutability: "nonpayable" },
  // ── Events ────────────────────────────────────────────────────
  { type: "event", name: "CountryMinted",          inputs: [{ name: "user", type: "address", indexed: true }, { name: "countryId", type: "uint256", indexed: true }, { name: "amount", type: "uint256" }, { name: "timestamp", type: "uint256" }] },
  { type: "event", name: "TicketPurchased",        inputs: [{ name: "user", type: "address", indexed: true }, { name: "quantity", type: "uint256" }, { name: "timestamp", type: "uint256" }] },
  { type: "event", name: "VoteCast",               inputs: [{ name: "user", type: "address", indexed: true }, { name: "playerName", type: "string" }, { name: "votes", type: "uint256" }, { name: "timestamp", type: "uint256" }] },
  { type: "event", name: "NationsCupClaimed",      inputs: [{ name: "user", type: "address", indexed: true }, { name: "reward", type: "uint256" }, { name: "timestamp", type: "uint256" }] },
  { type: "event", name: "TopScorerClaimed",       inputs: [{ name: "user", type: "address", indexed: true }, { name: "reward", type: "uint256" }, { name: "timestamp", type: "uint256" }] },
  { type: "event", name: "UnusedTicketsRefunded",  inputs: [{ name: "user", type: "address", indexed: true }, { name: "ticketCount", type: "uint256" }, { name: "refundAmount", type: "uint256" }, { name: "timestamp", type: "uint256" }] },
  { type: "event", name: "MaintenanceModeChanged", inputs: [{ name: "maintenance", type: "bool" }] },
  { type: "event", name: "CountryEliminatedEvent", inputs: [{ name: "countryId", type: "uint256", indexed: true }] },
  { type: "event", name: "NationsCupFinalized",    inputs: [{ name: "winningId", type: "uint256", indexed: true }, { name: "totalPoolSize", type: "uint256" }] },
  { type: "event", name: "TopScorerFinalizedEvent",inputs: [{ name: "playerName", type: "string" }, { name: "totalPoolSize", type: "uint256" }] },
] as const;
